import type { PageSEO } from "../seo-data";

const SITE_URL = "https://istanbulbariatriccenter.com";

const faqItems = [
  ["How much is gastric bypass in Turkey in 2026?", "At Istanbul Bariatric Center, Roux-en-Y gastric bypass costs £5,000 for the recommended Relaxation package and £5,350 for Luxury. Both include surgery by Dr Üstün, two nights at Liv Hospital Vadistanbul, hotel accommodation, transfers and 12 months of WhatsApp aftercare including UK-registered dietitian support. Private UK treatment typically costs £10,000–£15,000."],
  ["What is the difference between gastric bypass and mini gastric bypass?", "Roux-en-Y uses two anastomoses in a Y-configuration; mini bypass, or OAGB, uses one anastomosis and a longer tubular pouch. OAGB is technically simpler and slightly quicker, while RYGB has a lower long-term bile-reflux risk and may be preferred after a failed sleeve. Weight-loss and diabetes-remission outcomes are broadly similar at five to seven years."],
  ["Is gastric bypass reversible?", "Technically yes, but reversal is a major operation and is rarely performed. Patients should treat gastric bypass as a permanent decision."],
  ["Which is better — gastric sleeve or gastric bypass?", "Neither is universally better. Sleeve is simpler and recovery is usually quicker. Bypass generally produces greater long-term weight loss and diabetes remission, and is often preferred for severe GORD or a large hiatus hernia. The decision depends on BMI, reflux, diabetes, anatomy and previous surgery."],
  ["How much weight will I lose after gastric bypass?", "Average excess weight loss is 65–80% at 18–24 months, roughly 30–35% of total starting body weight. Individual results vary with starting health, eating, activity and engagement with follow-up."],
  ["Does gastric bypass cure type-2 diabetes?", "Bypass can produce remission, not a permanent cure, in around 74% of people with type 2 diabetes at one year, decreasing to 38–54% at five years and beyond. Outcomes are often better with shorter disease duration and no insulin use. Medication must only be changed under clinical supervision."],
  ["What is dumping syndrome and how common is it?", "Dumping occurs when sugary or high-fat food passes too quickly from the pouch into the small intestine. Early dumping, 15–30 minutes after eating, can cause nausea, cramps and sweating; late dumping, one to three hours later, can cause low blood sugar. Some form affects 50–70% of RYGB patients in the early months and usually settles by month 6–12."],
  ["How long is recovery from gastric bypass?", "The package includes two hospital nights. Desk work may resume at 10–14 days, physical work at about four weeks and gym activity at six weeks after clearance. The phased diet progresses from liquids to purée, soft solids and a full diet over about six weeks."],
  ["What supplements will I need for life?", "Typical lifelong care includes a daily bariatric multivitamin, calcium citrate 1,200–1,500 mg, vitamin D3 2,000–3,000 IU, oral iron and vitamin B12 injections every three months or prescribed high-dose oral B12. Annual blood tests monitor iron, B12, folate, vitamin D, calcium and PTH."],
  ["Can gastric bypass be revised if it fails?", "Yes. Depending on the cause, options can include pouch revision, distalisation, conversion to another operation or endoscopic TORe to reduce a dilated outlet. Revision is more complex than primary surgery and requires detailed assessment. Dr Üstün has handled 300+ complex revisional cases."],
  ["Is gastric bypass safe in Turkey?", "No operation is risk-free. Safety depends on selection, surgeon experience, hospital resources and follow-up. Dr Üstün has performed 700+ bypass procedures, and care takes place at JCI-accredited Liv Hospital Vadistanbul with intensive care, imaging and interventional support."],
  ["How many days do I stay in Istanbul for bypass?", "The Relaxation itinerary is seven days and six nights: two nights in hospital and four nights in a 5-star hotel. Luxury includes two hospital nights and five nights in a luxury hotel. Confirm your personal itinerary before booking flights."],
];

export const gastricBypassSEO: PageSEO = {
  title: "Gastric Bypass Turkey 2026: Cost and Recovery",
  description: "Compare Roux-en-Y bypass costs, candidacy, recovery and risks in Turkey. Dr Üstün's all-inclusive Relaxation and Luxury packages start at £5,000.",
  h1: "Gastric Bypass Surgery in Turkey — Roux-en-Y, Cost, Recovery",
  bodyExcerpt: "Roux-en-Y gastric bypass in Turkey costs from £5,000 at Istanbul Bariatric Center. Compare sleeve and OAGB, packages, international prices, candidacy, procedure steps, recovery, risks, lifelong nutrition and aftercare.",
  canonical: SITE_URL + "/gastric-bypass",
  richContent:
    "<section><h2>Quick answer</h2><p>Roux-en-Y gastric bypass in Turkey costs from £5,000 all-inclusive at Istanbul Bariatric Center, performed by Op. Dr Murat Üstün, who has 25+ years of experience and 700+ bypass cases, at JCI-accredited Liv Hospital Vadistanbul. Bypass may be preferred for severe GORD, poorly controlled type 2 diabetes, BMI 45 or above, or a previous bariatric operation. Relaxation includes surgeon and anaesthetist fees, two hospital nights, four 5-star hotel nights, VIP transfers, half-board meals, a supplements pack and 12 months of WhatsApp aftercare including UK-registered dietitian support.</p></section>" +
    "<section><h2>Gastric sleeve vs mini gastric bypass vs Roux-en-Y bypass</h2><p>All three are laparoscopic and can work well, but they suit different patients. Dr Üstün considers BMI, reflux, diabetes and previous surgery.</p><table><thead><tr><th>Feature</th><th>Gastric Sleeve</th><th>Mini Bypass (OAGB)</th><th>Roux-en-Y (RYGB)</th></tr></thead><tbody><tr><td>How it works</td><td>Removes about 80% of stomach</td><td>Long pouch, one join, bypasses about 2 m bowel</td><td>Small pouch and Y-shaped reconnection</td></tr><tr><td>Anastomoses</td><td>0</td><td>1</td><td>2</td></tr><tr><td>Operating time</td><td>45–75 min</td><td>60–90 min</td><td>90–120 min</td></tr><tr><td>Hospital stay</td><td>2 nights</td><td>2 nights</td><td>2 nights</td></tr><tr><td>Excess weight loss at 2 years</td><td>60–70%</td><td>70–80%</td><td>65–80%</td></tr><tr><td>Diabetes remission at 1 year</td><td>About 60%</td><td>About 70%</td><td>About 74%</td></tr><tr><td>Reflux impact</td><td>Can worsen</td><td>Slight bile reflux risk</td><td>Usually improves reflux</td></tr><tr><td>Reversible</td><td>No</td><td>Partly</td><td>Technically, but rarely done</td></tr><tr><td>Lifelong B12 injection</td><td>Not usually</td><td>Yes</td><td>Yes</td></tr><tr><td>Price at IBC</td><td>from £2,450</td><td>from £5,000</td><td>from £5,000</td></tr></tbody></table><p>Read about <a href=\"/mini-gastric-bypass\">one-anastomosis (OAGB) mini bypass</a>, compare <a href=\"/gastric-sleeve-turkey\">gastric sleeve Turkey</a>, or learn <a href=\"/sleeve-gastrectomy\">how sleeve gastrectomy works</a>.</p></section>" +
    "<section><h2>Cost of gastric bypass in Turkey — 2026 packages</h2><p>Both packages include surgery by Dr Üstün at Liv Hospital Vadistanbul.</p><table><thead><tr><th>Feature</th><th>Relaxation — recommended</th><th>Luxury</th></tr></thead><tbody><tr><td>Price</td><td>£5,000</td><td>£5,350</td></tr><tr><td>Hospital</td><td>Liv Vadistanbul JCI, 2 nights</td><td>Liv Vadistanbul JCI suite, 2 nights</td></tr><tr><td>Hotel</td><td>4 nights in a 5-star hotel</td><td>5 nights in a luxury hotel</td></tr><tr><td>Medical fees</td><td>Surgeon and anaesthetist fees</td><td>Surgeon and anaesthetist fees</td></tr><tr><td>Tests and medication</td><td>All pre-op tests and medications</td><td>All pre-op tests and medications</td></tr><tr><td>Transfers</td><td>VIP airport and hospital transfers</td><td>Private VIP car throughout</td></tr><tr><td>Meals</td><td>Half board</td><td>Full board with companion allowance</td></tr><tr><td>Aftercare</td><td>12 months via WhatsApp including UK-registered dietitian support</td><td>12 months priority aftercare including UK-registered dietitian support</td></tr><tr><td>Supplements</td><td>Supplements starter pack</td><td>Supplements starter pack</td></tr></tbody></table></section>" +
    "<section><h2>Turkey vs UK, Germany, USA and Australia — 2026 bypass cost</h2><table><thead><tr><th>Country</th><th>Typical self-pay cost</th><th>Waiting time</th><th>Hospital nights</th></tr></thead><tbody><tr><td>Turkey (IBC)</td><td>£5,000 – £5,350 all-inclusive</td><td>2–4 weeks</td><td>2 nights</td></tr><tr><td>United Kingdom private</td><td>£10,000 – £15,000, sometimes up to £18k</td><td>4–8 weeks</td><td>2–3 nights</td></tr><tr><td>United Kingdom NHS</td><td>Free at point of use</td><td>2–5 years</td><td>2–3 nights</td></tr><tr><td>Germany private</td><td>€12,000 – €22,000, about £10,300–£18,800</td><td>1–3 months</td><td>2–3 nights</td></tr><tr><td>United States self-pay</td><td>$15,000 – $35,000, about £11,900–£27,800</td><td>2–4 weeks</td><td>2–3 nights</td></tr><tr><td>Australia self-funded</td><td>AUD $18k – $28k, about £9,500–£14,700</td><td>2–4 weeks</td><td>2 nights</td></tr></tbody></table><p>Guide prices checked September 2026. Currency movement and individual medical needs can change quotations.</p></section>" +
    "<section><h2>What’s included in the all-inclusive package</h2><h3>Medical and surgical</h3><ul><li>Pre-operative bloods, HbA1c, ECG and further tests when indicated</li><li>Upper GI endoscopy, hiatus assessment and anaesthetic consultation</li><li>Laparoscopic Roux-en-Y gastric bypass by Dr Üstün</li><li>Surgeon and anaesthetist fees, staplers and consumables</li><li>Two nights at JCI-accredited Liv Hospital Vadistanbul</li><li>Hospital medications and post-operative leak testing</li></ul><h3>Travel, stay and aftercare</h3><ul><li>Four 5-star hotel nights on Relaxation or five luxury-hotel nights on Luxury</li><li>VIP transfers, upgraded to a private car throughout on Luxury</li><li>Half board on Relaxation or full board with companion allowance on Luxury</li><li>English-speaking coordination and a personalised phased-diet plan</li><li>Supplements starter pack</li><li>12 months of WhatsApp aftercare including UK-registered dietitian support</li></ul></section>" +
    "<section><h2>When bypass beats sleeve — who should choose Roux-en-Y</h2><p>Roux-en-Y may be preferred for severe GORD, a large hiatus hernia, BMI 45 or above, poorly controlled or insulin-treated type 2 diabetes, revision after a failed band or sleeve, Barrett’s oesophagus or severe oesophagitis. Selection is individual. Read about <a href=\"/reflux-after-gastric-sleeve\">reflux after gastric sleeve</a> and <a href=\"/revision-bariatric-surgery\">revision bariatric surgery</a>.</p></section>" +
    "<section><h2>How Roux-en-Y gastric bypass works</h2><p>RYGB is performed under general anaesthesia through four or five small keyhole incisions and usually takes 90–120 minutes.</p><h3>Step 1 — Create the pouch</h3><p>The upper stomach is divided to make a pouch of about 30 ml. The remnant stays in place but food no longer passes through it.</p><h3>Step 2 — Divide the small bowel</h3><p>The jejunum is divided about 50 cm below the stomach. The downstream end becomes the Roux limb and the other carries bile and pancreatic juice.</p><h3>Step 3 — Gastrojejunostomy</h3><p>The Roux limb is joined to the pouch, so food bypasses the remnant stomach, duodenum and proximal jejunum.</p><h3>Step 4 — Jejunojejunostomy</h3><p>The biliopancreatic limb rejoins the Roux limb 100–150 cm farther down. Mesenteric defects are closed to reduce internal-hernia risk.</p><p>Altered gut-hormone signalling, bile-acid circulation and the microbiome help explain rapid metabolic improvement.</p></section>" +
    "<section><h2>Recovery timeline — day 0 to month 24</h2><table><thead><tr><th>When</th><th>What to expect</th><th>Diet</th></tr></thead><tbody><tr><td>Day 0</td><td>Recovery, sips and a short walk</td><td>Water</td></tr><tr><td>Day 1</td><td>Leak test and corridor walks</td><td>Clear fluids and protein sips</td></tr><tr><td>Day 2</td><td>Discharge to hotel when ready</td><td>Clear fluids and protein drinks</td></tr><tr><td>Days 3–7</td><td>Hotel rest and gradually longer walks</td><td>Full liquids</td></tr><tr><td>Week 2</td><td>Desk work may resume</td><td>Liquids to thin purée</td></tr><tr><td>Weeks 3–4</td><td>Early weight loss</td><td>Purée</td></tr><tr><td>Weeks 5–6</td><td>Gentle exercise after clearance</td><td>Soft solids</td></tr><tr><td>Week 7 onward</td><td>Structured follow-up</td><td>Full diet and supplements</td></tr><tr><td>Month 3</td><td>Blood tests and supplement adjustment</td><td>Full diet and supplements</td></tr><tr><td>Month 6</td><td>Often 50–65% excess weight loss</td><td>Full diet and supplements</td></tr><tr><td>Months 12–24</td><td>Often 65–80% excess weight loss</td><td>Maintenance</td></tr></tbody></table></section>" +
    "<section><h2>Risks and complications — the honest picture</h2><p>Roux-en-Y is established but more complex than sleeve surgery. Published rates vary.</p><h3>Early complications — first 30 days</h3><table><thead><tr><th>Complication</th><th>Typical rate</th><th>Prevention or management</th></tr></thead><tbody><tr><td>Anastomotic leak</td><td>1–2%</td><td>Inspection, leak test and access to intervention</td></tr><tr><td>Bleeding requiring transfusion</td><td>1–3%</td><td>Vessel sealing, inspection and monitoring</td></tr><tr><td>DVT or pulmonary embolism</td><td>Under 1%</td><td>Blood-thinning medication, stockings and walking</td></tr><tr><td>Wound infection</td><td>1–3%</td><td>Antibiotics and careful closure</td></tr><tr><td>30-day mortality</td><td>About 0.2%</td><td>Careful selection and an experienced team</td></tr></tbody></table><h3>Late complications — weeks to years</h3><table><thead><tr><th>Complication</th><th>Typical rate</th><th>Management</th></tr></thead><tbody><tr><td>Dumping syndrome</td><td>50–70% at some point, usually mild</td><td>Avoid concentrated sugar and rapid carbohydrates</td></tr><tr><td>Marginal ulcer</td><td>5–10%</td><td>Acid suppression, no smoking and NSAID avoidance</td></tr><tr><td>Anastomotic stricture</td><td>3–7%</td><td>Endoscopic balloon dilatation</td></tr><tr><td>Internal hernia</td><td>2–5%</td><td>Defect closure and repair if needed</td></tr><tr><td>Gallstones</td><td>25–30%</td><td>Preventive medicine or treatment when symptomatic</td></tr><tr><td>Nutritional deficiency</td><td>Common without supplements</td><td>Lifelong supplements and blood tests</td></tr><tr><td>Post-bypass hypoglycaemia</td><td>1–5%</td><td>Dietary management, then medicine if needed</td></tr><tr><td>Weight regain after five years</td><td>20–30%</td><td>Nutrition review, endoscopic treatment or revision</td></tr></tbody></table></section>" +
    "<section><h2>Long-term nutrition and lifelong supplementation</h2><p>Typical care includes a daily bariatric multivitamin, calcium citrate 1,200–1,500 mg, vitamin D3 2,000–3,000 IU, prescribed oral iron, 60–80 g protein and vitamin B12 injections every three months or prescribed high-dose oral B12. Blood tests are required at months 3, 6 and 12, then annually. Bone-density monitoring may be advised. NSAIDs and smoking should be avoided, and alcohol requires particular caution.</p></section>" +
    "<section><h2>Why choose Dr Üstün and Liv Hospital Vadistanbul?</h2><h3>The surgeon</h3><p><a href=\"/dr-murat-ustun\">Op. Dr Murat Üstün</a>, MD, PhD has 25+ years of experience, 6,000+ advanced laparoscopic procedures and 700+ bypass cases. His memberships include BOMSS, IFSO and the International Bariatric Club. IBC received WhatClinic awards in 2019–2021 and 2023–2025.</p><h3>The hospital</h3><p>Care takes place at JCI-accredited Liv Hospital Vadistanbul with 24-hour intensive care, imaging, interventional support and English-speaking staff.</p></section>" +
    "<section><h2>Your 7-day gastric bypass journey in Istanbul</h2><table><thead><tr><th>Day</th><th>Plan</th></tr></thead><tbody><tr><td>Day 1 — Arrival</td><td>VIP pickup, hotel check-in and welcome call</td></tr><tr><td>Day 2 — Pre-op</td><td>Tests, endoscopy and consultation with Dr Üstün</td></tr><tr><td>Day 3 — Surgery</td><td>Roux-en-Y bypass lasting 90–120 minutes</td></tr><tr><td>Day 4 — Recovery</td><td>Leak test, first walks and clear fluids</td></tr><tr><td>Day 5 — Discharge</td><td>Discharge to hotel when clinically ready</td></tr><tr><td>Day 6 — Rest</td><td>Hotel rest, protein drinks and short walks</td></tr><tr><td>Day 7 — Fly home</td><td>Airport transfer with documents and aftercare plan</td></tr></tbody></table><p>Luxury adds a fifth hotel night. Confirm the individual itinerary before booking flights.</p></section>" +
    "<section><h2>Frequently asked questions</h2><h3>How much is gastric bypass in Turkey in 2026?</h3><p>Relaxation costs £5,000 and Luxury costs £5,350. Both include Dr Üstün, two Liv Hospital nights, hotel, transfers and 12 months of aftercare.</p><h3>What is the difference between gastric bypass and mini gastric bypass?</h3><p>Roux-en-Y uses two intestinal joins; OAGB uses one and a longer pouch. RYGB has a lower bile-reflux risk.</p><h3>Is gastric bypass reversible?</h3><p>Technically yes, but reversal is major surgery and rarely performed. Treat bypass as permanent.</p><h3>Which is better — gastric sleeve or gastric bypass?</h3><p>Neither is best for everyone. Bypass may suit severe reflux, diabetes, higher BMI or revision; sleeve is simpler.</p><h3>How much weight will I lose after gastric bypass?</h3><p>Average excess weight loss is 65–80% at 18–24 months, but individual results vary.</p><h3>Does gastric bypass cure type-2 diabetes?</h3><p>It can produce remission, not permanent cure. Around 74% are in remission at one year, decreasing over time.</p><h3>What is dumping syndrome and how common is it?</h3><p>Rapid passage of sugary or fatty food can cause digestive or low-blood-sugar symptoms. Some form affects 50–70% early on and usually settles.</p><h3>How long is recovery from gastric bypass?</h3><p>There are two hospital nights. Desk work may resume at 10–14 days and gym activity at six weeks after clearance.</p><h3>What supplements will I need for life?</h3><p>Typical care includes a bariatric multivitamin, calcium, vitamin D, iron and B12, with annual blood tests.</p><h3>Can gastric bypass be revised if it fails?</h3><p>Options may include pouch surgery, distalisation, conversion or endoscopic TORe after detailed assessment.</p><h3>Is gastric bypass safe in Turkey?</h3><p>No operation is risk-free. Selection, surgeon experience, hospital resources and follow-up all matter.</p><h3>How many days do I stay in Istanbul for bypass?</h3><p>Relaxation is seven days and six nights, with two hospital nights and four hotel nights. Luxury adds one hotel night.</p></section>" +
    "<section><h2>Book your free consultation with Dr Üstün</h2><p>Request a no-obligation clinical review. Dr Üstün will consider BMI, reflux, diabetes and previous surgery, then explain whether sleeve, OAGB or Roux-en-Y is suitable. Use the <a href=\"/contact\">contact form</a>.</p></section>" +
    "<section><h2>Related procedures and resources</h2><p>Continue with <a href=\"/mini-gastric-bypass\">one-anastomosis (OAGB) mini bypass</a>, <a href=\"/gastric-sleeve-turkey\">gastric sleeve Turkey</a>, <a href=\"/sleeve-gastrectomy\">how sleeve gastrectomy works</a>, <a href=\"/revision-bariatric-surgery\">revision bariatric surgery</a>, <a href=\"/reflux-after-gastric-sleeve\">reflux after gastric sleeve</a>, <a href=\"/dr-murat-ustun\">Dr Murat Üstün</a>, <a href=\"/results\">before and after results</a> or the <a href=\"/contact\">contact page</a>.</p><p>Reviewed by Op. Dr Murat Üstün, MD, PhD · Last reviewed 17 September 2026</p></section>",
  jsonLd: [
    {
      "@context": "https://schema.org",
      "@type": "MedicalWebPage",
      name: "Gastric Bypass Surgery in Turkey — Roux-en-Y, Cost, Recovery",
      url: SITE_URL + "/gastric-bypass",
      about: {
        "@type": "MedicalProcedure",
        name: "Roux-en-Y Gastric Bypass",
        procedureType: "Surgical",
        performedBy: { "@id": "https://istanbulbariatriccenter.com/#drmuratustun" },
        provider: { "@id": "https://istanbulbariatriccenter.com/#organization" },
        offers: [
          { "@type": "Offer", name: "Gastric Bypass Relaxation", price: "5000", priceCurrency: "GBP" },
          { "@type": "Offer", name: "Gastric Bypass Luxury", price: "5350", priceCurrency: "GBP" },
        ],
      },
      author: { "@id": "https://istanbulbariatriccenter.com/#drmuratustun" },
      publisher: { "@id": "https://istanbulbariatriccenter.com/#organization" },
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faqItems.map(([question, answer]) => ({
        "@type": "Question",
        name: question,
        acceptedAnswer: { "@type": "Answer", text: answer },
      })),
    },
  ],
};