import type { PageSEO } from "../seo-data";

const SITE_URL = "https://istanbulbariatriccenter.com";

export const gastricBypassSEO: PageSEO = {
  title: "Gastric Bypass Surgery in Turkey: 2026 Packages",
  description: "Compare Roux-en-Y and mini gastric bypass in Turkey with Dr Murat Üstün. Risks, recovery and all-inclusive Relaxation and Luxury packages from £5,000.",
  h1: "Gastric Bypass Surgery in Turkey",
  bodyExcerpt: "Gastric bypass surgery in Turkey includes Roux-en-Y gastric bypass and mini, or one-anastomosis, gastric bypass. Compare suitability, results, risks, recovery and transparent all-inclusive care with Dr Murat Üstün at JCI-accredited Liv Hospital Vadistanbul.",
  canonical: SITE_URL + "/gastric-bypass",
  richContent:
    "<section><h2>What is gastric bypass surgery?</h2><p>Gastric bypass is a family of bariatric operations that creates a smaller functional stomach pouch and reroutes part of the small intestine. The operation supports earlier fullness and metabolic change. This guide covers both Roux-en-Y gastric bypass, or RYGB, and one-anastomosis gastric bypass, also called OAGB or mini gastric bypass.</p><p>Procedure selection follows medical and nutritional assessment rather than a one-size-fits-all pathway. Patients researching the one-join operation can read the <a href=\"/mini-gastric-bypass\">dedicated mini gastric bypass guide</a>, while the <a href=\"/gastric-sleeve-vs-gastric-bypass\">sleeve versus bypass comparison</a> explains the main trade-offs.</p></section>" +
    "<section><h2>Roux-en-Y vs mini gastric bypass</h2><p>Roux-en-Y creates a small pouch and two intestinal joins. OAGB uses a longer pouch and one intestinal join. Both require lifelong nutritional monitoring. Reflux history, metabolic priorities, anatomy, previous surgery, medicines and the ability to follow aftercare all influence which approach is responsible.</p><p>OAGB is technically simpler, but bile reflux requires specific consideration. Roux-en-Y may be preferred where reflux influences the choice. The decision is individual and is not simply a matter of package price.</p></section>" +
    "<section><h2>Who may be suitable?</h2><p>Gastric bypass may be discussed for people with clinically significant obesity after appropriate non-surgical efforts, selected patients with type-2 diabetes, people whose reflux profile affects procedure choice, and some patients seeking revision after sleeve surgery. Candidates must be able to follow staged eating advice, prescribed supplements, blood tests and long-term clinical monitoring.</p><p>Pregnancy plans, active substance dependence, uncontrolled mental health conditions, untreated eating disorders, major anaesthetic risk or an inability to engage with aftercare may delay or rule out surgery. Consultation is an assessment, not automatic approval.</p></section>" +
    "<section><h2>Results and metabolic benefits</h2><p>A commonly used benchmark after gastric bypass is 70–80% excess weight loss. Outcomes cannot be guaranteed and are affected by starting health, procedure choice, eating behaviour, activity and engagement with follow-up. Gastric bypass also has a metabolic effect, with outcomes including up to 80% type-2 diabetes remission. Remission is not a permanent cure, and diabetes medicines must only be changed under clinical supervision.</p></section>" +
    "<section><h2>Risks and long-term responsibilities</h2><p>Recognised risks include bleeding, infection, blood clots, anaesthetic complications, leakage, stricture, bowel obstruction, internal hernia and ulcer. Dumping symptoms can occur, and deficiencies may develop without prescribed vitamins, minerals and blood monitoring. OAGB requires specific discussion of bile reflux. Weight regain remains possible, so gastric bypass should be understood as a clinical tool supported by lasting nutrition and behaviour changes.</p></section>" +
    "<section><h2>Recovery, diet and international aftercare</h2><p>The package includes three nights at Liv Hospital Vadistanbul. Recovery begins with monitoring, early walking and carefully introduced fluids, followed by a staged progression toward a suitable long-term eating pattern. Return to work, lifting, driving, exercise and flight timing are personalised rather than promised to a fixed schedule.</p><p>Patients receive support from a UK-registered dietitian. Protein, hydration and prescribed supplementation remain priorities. Persistent pain, fever, shortness of breath, vomiting or an inability to drink require prompt clinical contact. International patients should review the <a href=\"/bariatric-surgery-travel-guide\">bariatric surgery travel guide</a> before booking.</p></section>" +
    "<section><h2>Gastric bypass packages in Turkey</h2><p>The Gastric Bypass Relaxation package is £5,000. It includes surgery by Dr Murat Üstün, three nights at the JCI-accredited hospital, Radisson hotel accommodation, VIP airport transfers, all pre-operative tests, UK-registered dietitian support for 12 months and a supplements pack.</p><p>The Gastric Bypass Luxury package is £5,350. It adds an extended hotel stay, private VIP transfers throughout, a premium room and extended dietitian support. Relaxation is the recommended package. There is no basic gastric bypass package, and clinical assessment is required before a written treatment plan is confirmed.</p></section>" +
    "<section><h2>Why Istanbul Bariatric Center?</h2><p>Istanbul Bariatric Center was founded by Dr Murat Üstün, a bariatric and metabolic surgeon with 25+ years of experience and 6,000+ procedures. He is an IFSO member and a pioneer of ESG in Turkey. Surgery takes place at JCI-accredited Liv Hospital Vadistanbul. The clinic received WhatClinic Patient Service Awards in 2019–2021 and 2023–2025.</p></section>" +
    "<section><h2>Frequently asked questions</h2>" +
    "<h3>How much does gastric bypass surgery cost in Turkey?</h3><p>The Relaxation package is £5,000 and the Luxury package is £5,350. Both are all-inclusive options for clinically appropriate Roux-en-Y or OAGB surgery. There is no basic bypass package.</p>" +
    "<h3>Is gastric bypass surgery in Turkey safe?</h3><p>Every operation has risk. Safety depends on patient selection, surgical experience, hospital standards, anaesthesia assessment and aftercare. Dr Murat Üstün operates at JCI-accredited Liv Hospital Vadistanbul after reviewing medical suitability.</p>" +
    "<h3>What is the difference between Roux-en-Y and mini gastric bypass?</h3><p>Roux-en-Y uses two intestinal joins; mini bypass, or OAGB, uses one. Reflux profile, anatomy and metabolic priorities help determine which is suitable.</p>" +
    "<h3>How long is recovery after gastric bypass?</h3><p>The package includes three hospital nights. Diet, activity and return to work progress gradually according to individual recovery and clinical advice.</p>" +
    "<h3>Can gastric bypass put type-2 diabetes into remission?</h3><p>Outcomes include up to 80% type-2 diabetes remission, but it is not guaranteed or a permanent cure. Medicines must only be changed with clinical supervision.</p>" +
    "<h3>What is included in the package?</h3><p>Relaxation includes surgery, three hospital nights, Radisson hotel, VIP airport transfers, pre-operative tests, a supplements pack and UK-registered dietitian support for 12 months. Luxury adds extended hotel, private VIP transfers, premium room and extended dietitian support.</p>" +
    "<h3>Can a gastric sleeve be revised to gastric bypass?</h3><p>Selected patients may be considered for conversion because of significant reflux, inadequate weight loss or weight regain. Revision is more complex and needs detailed assessment.</p>" +
    "<h3>How much weight can I lose?</h3><p>A common benchmark is 70–80% excess weight loss, but individual results cannot be promised.</p></section>",
  jsonLd: [
    {
      "@context": "https://schema.org",
      "@type": "MedicalProcedure",
      "@id": SITE_URL + "/gastric-bypass#procedure",
      name: "Gastric Bypass Surgery",
      alternateName: ["Roux-en-Y Gastric Bypass", "RYGB", "One-Anastomosis Gastric Bypass", "OAGB", "Mini Gastric Bypass"],
      description: "Roux-en-Y and mini gastric bypass surgery in Turkey with all-inclusive care at Liv Hospital Vadistanbul.",
      procedureType: "https://schema.org/SurgicalProcedure",
      bodyLocation: "Stomach and small intestine",
      performedBy: { "@id": SITE_URL + "/#drmuratustun" },
      provider: { "@id": SITE_URL + "/#organization" },
      url: SITE_URL + "/gastric-bypass",
      offers: [
        { "@type": "Offer", name: "Gastric Bypass Relaxation", price: "5000", priceCurrency: "GBP", url: SITE_URL + "/gastric-bypass" },
        { "@type": "Offer", name: "Gastric Bypass Luxury", price: "5350", priceCurrency: "GBP", url: SITE_URL + "/gastric-bypass" },
      ],
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: [
        { "@type": "Question", name: "How much does gastric bypass surgery cost in Turkey?", acceptedAnswer: { "@type": "Answer", text: "At Istanbul Bariatric Center, the all-inclusive Gastric Bypass Relaxation package is £5,000 and the Luxury package is £5,350. These prices apply to both Roux-en-Y and mini (OAGB) bypass when clinically appropriate. There is no basic bypass package. Your written treatment plan confirms the recommended operation and everything included before you travel." } },
        { "@type": "Question", name: "Is gastric bypass surgery in Turkey safe?", acceptedAnswer: { "@type": "Answer", text: "Every operation has risk, and travelling abroad does not remove it. Safety depends on appropriate patient selection, an experienced bariatric surgeon, an accredited hospital, careful anaesthesia assessment and reliable aftercare. Dr Murat Üstün operates at JCI-accredited Liv Hospital Vadistanbul. Your medical history is reviewed before acceptance, and risks are discussed during consent." } },
        { "@type": "Question", name: "What is the difference between Roux-en-Y and mini gastric bypass?", acceptedAnswer: { "@type": "Answer", text: "Roux-en-Y gastric bypass creates a small stomach pouch and two intestinal joins. Mini gastric bypass, also called one-anastomosis gastric bypass or OAGB, uses a longer pouch and one join. OAGB is technically simpler, while Roux-en-Y may be preferred where bile reflux is a concern. The choice is individual, not simply a matter of price." } },
        { "@type": "Question", name: "How long is recovery after gastric bypass?", acceptedAnswer: { "@type": "Answer", text: "Recovery is gradual and varies with health, work and the exact procedure. The package includes three hospital nights. Patients then progress through a staged diet, increase gentle activity as advised and return to work only when the surgical team considers it appropriate. Heavy lifting and strenuous exercise wait until medical clearance." } },
        { "@type": "Question", name: "Can gastric bypass put type-2 diabetes into remission?", acceptedAnswer: { "@type": "Answer", text: "Gastric bypass has a strong metabolic effect and published outcomes include up to 80% type-2 diabetes remission. Remission is not guaranteed and is not the same as a permanent cure. Duration of diabetes, pancreatic function, medication use and weight response all influence the result, so medicines must only be changed under clinical supervision." } },
        { "@type": "Question", name: "What is included in the gastric bypass Turkey package?", acceptedAnswer: { "@type": "Answer", text: "The Relaxation package includes surgery by Dr Murat Üstün, three nights at the JCI-accredited hospital, Radisson hotel accommodation, VIP airport transfers, all pre-operative tests, a supplements pack and support from a UK-registered dietitian for 12 months. Luxury adds an extended hotel stay, private VIP transfers throughout, a premium room and extended dietitian support." } },
        { "@type": "Question", name: "Can a gastric sleeve be revised to gastric bypass?", acceptedAnswer: { "@type": "Answer", text: "A sleeve can sometimes be converted to Roux-en-Y or OAGB for significant reflux, inadequate weight loss or weight regain, but revision surgery is more complex than a primary operation. The surgeon needs the original operation details, current imaging or endoscopy where indicated, eating history and a full medical assessment before recommending a revision." } },
        { "@type": "Question", name: "How much weight can I lose after gastric bypass?", acceptedAnswer: { "@type": "Answer", text: "A commonly used benchmark is 70–80% excess weight loss, although an individual result cannot be promised. Starting weight, procedure choice, eating behaviour, activity, metabolic health and engagement with dietitian follow-up all matter. The aim is durable health improvement rather than reaching a particular number as quickly as possible." } },
      ],
    },
  ],
};
